deploy:
  provider: s3
  access_key_id: AKIAISASFZGXM5KDAGNQ
  secret_access_key:
    secure: jnXFLtTqPna7pdNQXyZmAQSybW4Yu1UN06ezB6isTvihd071LsOEkFzwuhHfw4+vxGlbVtCECFgV5R70VObXxeZ0YT/J4fpomeHx5fJGW/Dc8utD4uQr8Gi9OPP7nHG2yQm49C45dDB/9o2surDCFfP8FRHpA/Br+w3ITBPbVJ853pWf35x3QYo9SHNSQcCZaAjQ8pyN8e8X5Rl0UCY+mMbiknGeIQgfXTRui9QZmN8U7EZ+yMT9mNkuzAgVOt5yf/tOCPJaiJUuvFAsSzOZvEW3NSWV+BXMZgzKJ7SzIf5H8tjeiCBt3RyKWkxk7TH0qFJpxdwSWOc/RxPDLLKQ++CG1i6SVWfFXoWUlSMUuIaOSZTIoZBgkng2dVtXVPx6MySfCzsLMrfiXTLtki4dIFTBM/Z8IPajj4sbmfTdm2On/4GoPdCeYgmuiGM2L9oVCsolH5RLUAaxMpKrBy6Q0FyoJHfGpK0fVaEkQLH21C8x/I5lsxCjJ3mQIP5lPCvAXdMg967IBv+YA7XsLs5pMIKT1wf98FpW1HJ57a9rvV6wyE89iBDvk0CMNHj/2fuPZxtp6yksX6h6rG8GHuNkhD2GcGnofAxSjvF09RM8qLy31rufUrpKc6ja01PJyvdtQnMF8Cl1tCFZfCsetNppmQm9WP6LedWVd59WXZ9VJPc=
  bucket: owen.cafe
  upload-dir: brownian-music
  region: eu-west-1
  on:
    repo: 414owen/BrownianMusic
language: c
script:
- echo "hello"
